<?php

// This file is auto-generated by the admin editor. Do not modify manually.

return array (
  'web-dev-bootcamp' => 
  array (
    'title' => 'Web Development Bootcamp',
    'short' => 'Learn HTML, CSS, JavaScript, and PHP from scratch.',
    'description' => 'A comprehensive course covering the full stack of web development. From front-end technologies like HTML, CSS, and JavaScript to back-end with PHP and databases. Includes real-world projects and quizzes to test your knowledge.',
    'thumb' => '../images/course1.jpg',
    'instructor' => 'John Doe',
    'intro_video_id' => 'zOjov-2OZ0E',
    'level' => 'Beginner',
    'duration' => '8 Weeks',
    'language' => 'English',
    'prerequisites' => 
    array (
      0 => 'None',
    ),
    'category' => 'web',
    'tags' => 
    array (
      0 => 'html',
      1 => 'css',
      2 => 'javascript',
      3 => 'php',
    ),
    'syllabus' => 
    array (
      0 => 
      array (
        'title' => 'Section 1: HTML & CSS Basics',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Introduction to HTML5',
            'content' => 'HTML5 is the latest version of Hypertext Markup Language, the standard markup language for documents designed to be displayed in a web browser. It introduces new semantic elements like `<header>`, `<footer>`, `<article>`, `<section>`, and `<nav>`, as well as new form controls and APIs for multimedia and graphics.',
          ),
          1 => 
          array (
            'type' => 'video',
            'title' => 'Styling with CSS3',
            'videoId' => '1Rs2ND_M_sE',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Responsive Design with Flexbox',
            'content' => 'Responsive web design ensures that web pages render well on a variety of devices and window or screen sizes. Flexbox (Flexible Box Layout module) is a one-dimensional layout method for arranging items in rows or columns. It makes it easier to design flexible and responsive layout structures without using floats or positioning.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'HTML & CSS Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'What does HTML stand for?',
                'options' => 
                array (
                  0 => 'Hyper Text Markup Language',
                  1 => 'High Tech Modern Language',
                  2 => 'Hyperlink and Text Markup Language',
                ),
                'answer' => 0,
              ),
              1 => 
              array (
                'q' => 'Which CSS property is used to change the text color of an element?',
                'options' => 
                array (
                  0 => 'font-color',
                  1 => 'text-color',
                  2 => 'color',
                ),
                'answer' => 2,
              ),
              2 => 
              array (
                'q' => 'What is the correct HTML element for inserting a line break?',
                'options' => 
                array (
                  0 => '<break>',
                  1 => '<lb>',
                  2 => '<br>',
                ),
                'answer' => 2,
              ),
              3 => 
              array (
                'q' => 'Which CSS property controls the spacing between elements?',
                'options' => 
                array (
                  0 => 'padding',
                  1 => 'margin',
                  2 => 'border',
                ),
                'answer' => 1,
              ),
            ),
          ),
          4 => 
          array (
            'type' => 'video',
            'title' => 'CSS Grid Layouts',
            'videoId' => '7kVeCqQCxlk',
          ),
        ),
      ),
      1 => 
      array (
        'title' => 'Section 2: JavaScript Fundamentals',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Variables and Data Types',
            'content' => 'In JavaScript, variables are containers for storing data values. Data types classify what kind of value a variable holds, such as numbers, strings, booleans, objects, and symbols. Understanding these is fundamental to writing any JavaScript code.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'DOM Manipulation',
            'content' => 'The Document Object Model (DOM) is a programming interface for web documents. It represents the page structure as a tree of objects, allowing JavaScript to access and manipulate elements, content, and styles of a web page dynamically.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Events and Listeners',
            'content' => 'Events are actions or occurrences that happen in the system you are programming, which the system tells you about so you can respond to them. Event listeners are functions that wait for an event to occur and then execute a specific block of code in response.',
          ),
          3 => 
          array (
            'type' => 'text',
            'title' => 'Introduction to ES6+',
            'content' => 'ECMAScript 2015 (ES6) introduced significant enhancements to JavaScript, including arrow functions, `let` and `const` for variable declarations, template literals, destructuring assignments, and modules. These features greatly improve code readability and functionality.',
          ),
          4 => 
          array (
            'type' => 'quiz',
            'title' => 'JavaScript Fundamentals Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'Which keyword is used to declare a variable that cannot be reassigned?',
                'options' => 
                array (
                  0 => 'var',
                  1 => 'let',
                  2 => 'const',
                ),
                'answer' => 2,
              ),
              1 => 
              array (
                'q' => 'What does DOM stand for?',
                'options' => 
                array (
                  0 => 'Document Object Model',
                  1 => 'Data Object Model',
                  2 => 'Dynamic Object-Markup',
                ),
                'answer' => 0,
              ),
              2 => 
              array (
                'q' => 'Which operator is used for strict equality (value and type)?',
                'options' => 
                array (
                  0 => '==',
                  1 => '===',
                  2 => '=',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
      2 => 
      array (
        'title' => 'Section 3: Server-side with PHP',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Introduction to PHP',
            'content' => 'PHP (Hypertext Preprocessor) is a popular general-purpose scripting language especially suited to web development. It is fast, flexible, and pragmatic, powering everything from your blog to the most popular websites in the world.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Handling Forms',
            'content' => 'PHP is excellent for processing HTML forms. It can collect data from form fields, validate it, and then store it in a database or send it via email. Understanding how to securely handle form submissions is crucial for web applications.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Connecting to a Database',
            'content' => 'Most dynamic web applications rely on databases to store and retrieve data. PHP provides extensions like MySQLi and PDO to connect to various database systems, allowing you to perform CRUD (Create, Read, Update, Delete) operations.',
          ),
          3 => 
          array (
            'type' => 'text',
            'title' => 'Building a Simple CMS',
            'content' => 'A Content Management System (CMS) allows users to create, manage, and modify content on a website without specialized technical knowledge. Building a simple CMS in PHP involves user authentication, content creation/editing, and database interaction.',
          ),
          4 => 
          array (
            'type' => 'quiz',
            'title' => 'PHP Basics Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'Which symbol is used to denote a variable in PHP?',
                'options' => 
                array (
                  0 => '@',
                  1 => '$',
                  2 => '&',
                ),
                'answer' => 1,
              ),
              1 => 
              array (
                'q' => 'What is the superglobal variable used to collect form data after submitting an HTML form with method="post"?',
                'options' => 
                array (
                  0 => '$_GET',
                  1 => '$_REQUEST',
                  2 => '$_POST',
                ),
                'answer' => 2,
              ),
              2 => 
              array (
                'q' => 'Which function is used to print text to the screen in PHP?',
                'options' => 
                array (
                  0 => 'print()',
                  1 => 'echo',
                  2 => 'display()',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
    ),
    'resources' => 
    array (
      0 => 
      array (
        'label' => 'MDN Web Docs',
        'url' => 'https://developer.mozilla.org/',
      ),
      1 => 
      array (
        'label' => 'W3Schools',
        'url' => 'https://www.w3schools.com/',
      ),
    ),
    'related' => 
    array (
      0 => 'advanced-php-mysql',
      1 => 'ui-ux-design-fundamentals',
    ),
  ),
  'advanced-php-mysql' => 
  array (
    'title' => 'Advanced PHP & MySQL',
    'short' => 'Master server-side logic and database management.',
    'description' => 'Take your PHP skills to the next level. This course covers object-oriented PHP, design patterns, security best practices, and advanced MySQL query optimization. Perfect for building robust, scalable web applications.',
    'thumb' => '../images/course2.jpg',
    'intro_video_id' => '',
    'instructor' => 'Jane Smith',
    'level' => 'Intermediate',
    'duration' => '6 Weeks',
    'language' => 'English',
    'prerequisites' => 
    array (
      0 => 'Basic PHP knowledge',
      1 => 'Understanding of HTML',
    ),
    'category' => 'web',
    'tags' => 
    array (
      0 => 'php',
      1 => 'mysql',
      2 => 'oop',
      3 => 'database',
      4 => 'backend',
    ),
    'syllabus' => 
    array (
      0 => 
      array (
        'title' => 'Section 1: Object-Oriented PHP',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Classes and Objects',
            'content' => 'Object-Oriented Programming (OOP) in PHP revolves around classes and objects. A class is a blueprint for creating objects, providing initial values for state (member variables) and implementations of behavior (member functions). An object is an instance of a class.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Inheritance and Polymorphism',
            'content' => 'Inheritance allows a class to inherit properties and methods from another class, promoting code reuse. Polymorphism enables objects of different classes to be treated as objects of a common type, often through method overriding or interfaces.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Namespaces and Autoloading',
            'content' => 'Namespaces solve the problem of name collisions between different libraries or components. Autoloading automatically loads class files when they are needed, eliminating the need for manual `require` or `include` statements.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'OOP in PHP Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'What is a "class" in OOP?',
                'options' => 
                array (
                  0 => 'An instance of an object',
                  1 => 'A blueprint for creating objects',
                  2 => 'A function',
                ),
                'answer' => 1,
              ),
              1 => 
              array (
                'q' => 'What concept allows a class to use properties and methods of another class?',
                'options' => 
                array (
                  0 => 'Polymorphism',
                  1 => 'Encapsulation',
                  2 => 'Inheritance',
                ),
                'answer' => 2,
              ),
              2 => 
              array (
                'q' => 'Which keyword is used to create an object from a class?',
                'options' => 
                array (
                  0 => 'object',
                  1 => 'new',
                  2 => 'instance',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
      1 => 
      array (
        'title' => 'Section 2: Advanced Database Design',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Database Indexing',
            'content' => 'Database indexing is a technique used to speed up data retrieval operations on a database table. An index is a special lookup table that the database search engine can use to speed up data retrieval. Think of it like an index in a book.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Query Optimization',
            'content' => 'Query optimization is the process of finding the most efficient way to execute a SQL query. This involves analyzing the query, table structures, and indexes to minimize resource consumption (CPU, I/O) and execution time.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Transactions and Stored Procedures',
            'content' => 'Transactions ensure data integrity by grouping multiple database operations into a single, atomic unit. Stored procedures are pre-compiled SQL code blocks stored in the database, which can be executed multiple times, improving performance and security.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'Database Design Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'What is the primary purpose of a database index?',
                'options' => 
                array (
                  0 => 'To enforce data types',
                  1 => 'To speed up data retrieval',
                  2 => 'To store large files',
                ),
                'answer' => 1,
              ),
              1 => 
              array (
                'q' => 'A group of SQL statements that execute as a single unit is called a:',
                'options' => 
                array (
                  0 => 'Stored Procedure',
                  1 => 'Trigger',
                  2 => 'Transaction',
                ),
                'answer' => 2,
              ),
              2 => 
              array (
                'q' => 'Which SQL clause is used to combine rows from two or more tables?',
                'options' => 
                array (
                  0 => 'GROUP BY',
                  1 => 'ORDER BY',
                  2 => 'JOIN',
                ),
                'answer' => 2,
              ),
            ),
          ),
        ),
      ),
    ),
    'resources' => 
    array (
      0 => 
      array (
        'label' => 'PHP The Right Way',
        'url' => 'https://phptherightway.com/',
      ),
    ),
    'related' => 
    array (
      0 => 'web-dev-bootcamp',
      1 => 'data-science-essentials',
    ),
  ),
  'data-science-essentials' => 
  array (
    'title' => 'Data Science Essentials',
    'short' => 'Master data analysis, visualization, and machine learning basics.',
    'description' => 'Begin your journey into the world of data science. This course introduces you to data analysis, visualization techniques, and the fundamentals of machine learning using Python and popular libraries like Pandas, Matplotlib, and Scikit-learn.',
    'thumb' => '../images/course3.jpg',
    'intro_video_id' => '',
    'instructor' => 'Alex Lee',
    'level' => 'Beginner',
    'duration' => '10 Weeks',
    'language' => 'English',
    'prerequisites' => 
    array (
      0 => 'Basic Python knowledge (optional)',
    ),
    'category' => 'data',
    'tags' => 
    array (
      0 => 'data',
      1 => 'python',
      2 => 'ml',
      3 => 'visualization',
    ),
    'syllabus' => 
    array (
      0 => 
      array (
        'title' => 'Section 1: Introduction to Python for Data Science',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Jupyter Notebooks',
            'content' => 'Jupyter Notebook is an open-source web application that allows you to create and share documents containing live code, equations, visualizations, and narrative text. It\'s widely used in data science for interactive data analysis and prototyping.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'NumPy Arrays',
            'content' => 'NumPy (Numerical Python) is a fundamental package for scientific computing with Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It\'s the basis for many other data science libraries.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Pandas DataFrames',
            'content' => 'Pandas is a powerful, flexible, and easy-to-use open-source data analysis and manipulation tool, built on top of the Python programming language. Its core data structure, the DataFrame, is a two-dimensional labeled data structure with columns of potentially different types.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'Python for Data Science Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'Which library is primarily used for creating and manipulating DataFrames in Python?',
                'options' => 
                array (
                  0 => 'NumPy',
                  1 => 'Pandas',
                  2 => 'Matplotlib',
                ),
                'answer' => 1,
              ),
              1 => 
              array (
                'q' => 'What is a primary advantage of NumPy arrays over standard Python lists?',
                'options' => 
                array (
                  0 => 'They can store mixed data types',
                  1 => 'They are faster for numerical operations',
                  2 => 'They have dynamic sizing',
                ),
                'answer' => 1,
              ),
              2 => 
              array (
                'q' => 'How do you start a single-line comment in Python?',
                'options' => 
                array (
                  0 => '//',
                  1 => '/*',
                  2 => '#',
                ),
                'answer' => 2,
              ),
            ),
          ),
        ),
      ),
      1 => 
      array (
        'title' => 'Section 2: Data Visualization',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Plotting with Matplotlib',
            'content' => 'Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It\'s a foundational plotting library, allowing you to create a wide variety of plots, from simple line plots to complex 3D visualizations.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Advanced charts with Seaborn',
            'content' => 'Seaborn is a Python data visualization library based on Matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics. Seaborn simplifies the creation of complex visualizations like heatmaps, violin plots, and pair plots.',
          ),
          2 => 
          array (
            'type' => 'quiz',
            'title' => 'Data Visualization Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'Seaborn is built on top of which other Python library?',
                'options' => 
                array (
                  0 => 'Pandas',
                  1 => 'NumPy',
                  2 => 'Matplotlib',
                ),
                'answer' => 2,
              ),
              1 => 
              array (
                'q' => 'Which type of plot is best for showing the distribution of a single numerical variable?',
                'options' => 
                array (
                  0 => 'Scatter Plot',
                  1 => 'Line Plot',
                  2 => 'Histogram',
                ),
                'answer' => 2,
              ),
              2 => 
              array (
                'q' => 'Which plot is used to show the relationship between two numerical variables?',
                'options' => 
                array (
                  0 => 'Bar Chart',
                  1 => 'Scatter Plot',
                  2 => 'Pie Chart',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
    ),
    'resources' => 
    array (
      0 => 
      array (
        'label' => 'Kaggle Datasets',
        'url' => 'https://www.kaggle.com/datasets',
      ),
    ),
    'related' => 
    array (
      0 => 'advanced-php-mysql',
    ),
  ),
  'ui-ux-design-fundamentals' => 
  array (
    'title' => 'UI/UX Design Fundamentals',
    'short' => 'Explore the principles of user interface and user experience design.',
    'description' => 'Learn to create intuitive and beautiful user interfaces. This course covers the fundamentals of user experience (UX) research, wireframing, prototyping, and user interface (UI) design principles. You\'ll work with tools like Figma to bring your ideas to life.',
    'thumb' => '../images/course4.jpg',
    'intro_video_id' => '',
    'instructor' => 'Emily Clark',
    'level' => 'Beginner',
    'duration' => '5 Weeks',
    'language' => 'English',
    'prerequisites' => 
    array (
      0 => 'None',
    ),
    'category' => 'design',
    'tags' => 
    array (
      0 => 'ui',
      1 => 'ux',
      2 => 'design',
      3 => 'figma',
    ),
    'syllabus' => 
    array (
      0 => 
      array (
        'title' => 'Section 1: Introduction to UX',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'User Research Methods',
            'content' => 'User research involves understanding user behaviors, needs, and motivations through various methods like interviews, surveys, and usability testing. It\'s crucial for designing products that truly meet user expectations.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Creating User Personas',
            'content' => 'User personas are fictional, generalized representations of your ideal customers. They help designers understand users\' needs, experiences, behaviors, and goals, making the design process more user-centered.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Journey Mapping',
            'content' => 'Customer journey mapping is a visualization of the process a customer goes through to accomplish a goal with your company. It helps identify pain points and opportunities for improvement in the user experience.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'UX Introduction Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'A fictional representation of an ideal customer is called a:',
                'options' => 
                array (
                  0 => 'User Story',
                  1 => 'User Persona',
                  2 => 'User Flow',
                ),
                'answer' => 1,
              ),
              1 => 
              array (
                'q' => 'What is the primary goal of user research?',
                'options' => 
                array (
                  0 => 'To validate the design',
                  1 => 'To understand user behaviors and needs',
                  2 => 'To test the code',
                ),
                'answer' => 1,
              ),
              2 => 
              array (
                'q' => 'A low-fidelity, basic layout of a design is called a...?',
                'options' => 
                array (
                  0 => 'Prototype',
                  1 => 'Mockup',
                  2 => 'Wireframe',
                ),
                'answer' => 2,
              ),
            ),
          ),
        ),
      ),
      1 => 
      array (
        'title' => 'Section 2: UI Design Principles',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Color Theory',
            'content' => 'Color theory in UI design involves understanding how colors affect user perception and emotion. It covers concepts like color harmony, contrast, and accessibility to create visually appealing and functional interfaces.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Typography',
            'content' => 'Typography is the art and technique of arranging type to make written language legible, readable, and appealing when displayed. Good typography enhances user experience by improving clarity and visual hierarchy.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Layout and Composition',
            'content' => 'Layout and composition refer to the arrangement of visual elements on a page. Principles like balance, alignment, proximity, and repetition are used to create organized, aesthetically pleasing, and easy-to-navigate interfaces.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'UI Design Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'The art of arranging type to make it legible and appealing is called:',
                'options' => 
                array (
                  0 => 'Color Theory',
                  1 => 'Layout',
                  2 => 'Typography',
                ),
                'answer' => 2,
              ),
              1 => 
              array (
                'q' => 'Which principle helps create a sense of unity by placing related items together?',
                'options' => 
                array (
                  0 => 'Proximity',
                  1 => 'Contrast',
                  2 => 'Repetition',
                ),
                'answer' => 0,
              ),
              2 => 
              array (
                'q' => 'The principle of creating a clear path for the user\'s eye to follow is called...?',
                'options' => 
                array (
                  0 => 'Balance',
                  1 => 'Visual Hierarchy',
                  2 => 'White Space',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
    ),
    'resources' => 
    array (
      0 => 
      array (
        'label' => 'Nielsen Norman Group',
        'url' => 'https://www.nngroup.com/',
      ),
    ),
    'related' => 
    array (
      0 => 'web-dev-bootcamp',
    ),
  ),
  'digital-marketing-crash-course' => 
  array (
    'title' => 'Digital Marketing Crash Course',
    'short' => 'Understand SEO, content marketing, and social media strategy.',
    'description' => 'This course provides a comprehensive overview of digital marketing. You will learn about Search Engine Optimization (SEO), content creation, social media marketing, email campaigns, and how to analyze marketing data to drive growth.',
    'thumb' => '../images/course5.jpg',
    'intro_video_id' => '',
    'instructor' => 'Dr. Watson',
    'level' => 'Beginner',
    'duration' => '4 Weeks',
    'language' => 'English',
    'prerequisites' => 
    array (
      0 => 'None',
    ),
    'category' => 'marketing',
    'tags' => 
    array (
      0 => 'seo',
      1 => 'marketing',
      2 => 'social media',
    ),
    'syllabus' => 
    array (
      0 => 
      array (
        'title' => 'Section 1: SEO Fundamentals',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Keyword Research',
            'content' => 'Keyword research is the process of finding and analyzing actual search terms that people enter into search engines. It helps you understand what topics people are interested in and how popular those topics are, guiding your content strategy.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'On-Page SEO',
            'content' => 'On-page SEO refers to optimizing individual web pages to rank higher and earn more relevant traffic in search engines. This includes optimizing title tags, meta descriptions, headings, content, and internal links.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Link Building',
            'content' => 'Link building is the process of acquiring hyperlinks from other websites to your own. A high quantity of high-quality backlinks can significantly improve a website\'s search engine visibility and ranking.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'SEO Fundamentals Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'Optimizing title tags and meta descriptions is part of:',
                'options' => 
                array (
                  0 => 'Off-Page SEO',
                  1 => 'Technical SEO',
                  2 => 'On-Page SEO',
                ),
                'answer' => 2,
              ),
              1 => 
              array (
                'q' => 'Acquiring hyperlinks from other websites to your own is called:',
                'options' => 
                array (
                  0 => 'Keyword Stuffing',
                  1 => 'Link Building',
                  2 => 'Content Marketing',
                ),
                'answer' => 1,
              ),
              2 => 
              array (
                'q' => 'The words and phrases that searchers enter into search engines are called...?',
                'options' => 
                array (
                  0 => 'Meta Tags',
                  1 => 'Keywords',
                  2 => 'Backlinks',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
      1 => 
      array (
        'title' => 'Section 2: Social Media Strategy',
        'lessons' => 
        array (
          0 => 
          array (
            'type' => 'text',
            'title' => 'Choosing the Right Platforms',
            'content' => 'Selecting the appropriate social media platforms is crucial for effective digital marketing. It depends on your target audience, content type, and business goals. Each platform has unique demographics and best practices.',
          ),
          1 => 
          array (
            'type' => 'text',
            'title' => 'Content Calendars',
            'content' => 'A content calendar is a written schedule of when and where you plan to publish upcoming content. It helps organize your social media efforts, ensures consistency, and allows for strategic planning of campaigns.',
          ),
          2 => 
          array (
            'type' => 'text',
            'title' => 'Analyzing Metrics',
            'content' => 'Analyzing social media metrics involves tracking and evaluating data related to your social media performance. Key metrics include reach, engagement, conversions, and audience growth, which help measure the effectiveness of your strategy.',
          ),
          3 => 
          array (
            'type' => 'quiz',
            'title' => 'Social Media Quiz',
            'questions' => 
            array (
              0 => 
              array (
                'q' => 'A written schedule for when and where you plan to publish content is a:',
                'options' => 
                array (
                  0 => 'Content Calendar',
                  1 => 'Marketing Plan',
                  2 => 'Engagement Report',
                ),
                'answer' => 0,
              ),
              1 => 
              array (
                'q' => 'Metrics like likes, comments, and shares are collectively known as:',
                'options' => 
                array (
                  0 => 'Reach',
                  1 => 'Impressions',
                  2 => 'Engagement',
                ),
                'answer' => 2,
              ),
              2 => 
              array (
                'q' => 'Which platform is primarily known for professional networking?',
                'options' => 
                array (
                  0 => 'Facebook',
                  1 => 'LinkedIn',
                  2 => 'Instagram',
                ),
                'answer' => 1,
              ),
            ),
          ),
        ),
      ),
    ),
    'resources' => 
    array (
      0 => 
      array (
        'label' => 'Google Digital Garage',
        'url' => 'https://learndigital.withgoogle.com/digitalgarage/',
      ),
    ),
    'related' => 
    array (
    ),
  ),
  'd-s-a' => 
  array (
    'title' => 'Data Structure And Algorithms',
    'short' => 'Data structures and algorithms (DSA) are two important aspects of any programming language.',
    'description' => 'Why to Learn Data Structures & Algorithms (DSA)?
As applications are getting complex and data rich, there are three common problems that applications face now-a-days.

Data Search − Consider an inventory of 1 million(106) items of a store. If the application is to search an item, it has to search an item in 1 million(106) items every time slowing down the search. As data grows, search will become slower.

Processor speed − Processor speed although being very high, falls limited if the data grows to billion records.

Multiple requests − As thousands of users can search data simultaneously on a web server, even the fast server fails while searching the data.

To solve the above-mentioned problems, data structures come to rescue. Data can be organized in a data structure in such a way that all items may not be required to be searched, and the required data can be searched almost instantly.

How to start learning Data Structures & Algorithms (DSA)?
The basic steps to learn DSA is as follows:

Step 1 - Learn Time and Space complexities
Time and Space complexities are the measures of the amount of time required to execute the code (Time Complexity) and amount of space required to execute the code (Space Complexity).

Step 2 - Learn Different Data Structures
Here we learn different types of data structures like Array, Stack, Queye, Linked List et.

Step 3 - Learn Different Algorithms
Once you have good undertanding about various data sturtcures then you can start learning associated algorithms to process the data stored in these data structures. These algorithms include searching, sorting, and other different algorithms.

Applications of Data Structures & Algorithms (DSA)
From the data structure point of view, following are some important categories of algorithms −

Search − Algorithm to search an item in a data structure.

Sort − Algorithm to sort items in a certain order.

Insert − Algorithm to insert item in a data structure.

Update − Algorithm to update an existing item in a data structure.

Delete − Algorithm to delete an existing item from a data structure.

The following computer problems can be solved using Data Structures −

Fibonacci number series
Knapsack problem
Tower of Hanoi
All pair shortest path by Floyd-Warshall
Shortest path by Dijkstra
Project scheduling
Who Should Learn DSA
This tutorial has been designed for Computer Science Students as well as Software Professionals who are willing to learn data Structures and Algorithm (DSA) Programming in simple and easy steps.

After completing this tutorial you will be at intermediate level of expertise from where you can take yourself to higher level of expertise.

DSA Online Editor & Compiler
In this tutorial, we will work with data structures and algorithms in four different programming languages: C, C++, Java, Python. So, we provide Online Compilers for each of these languages to execute the given code. Doing so, we are aiming to compromise the need for local setup for the compilers.',
    'thumb' => '../images/course_placeholder.jpg',
    'instructor' => 'Umesh Goyal',
    'intro_video_id' => '',
    'level' => 'Beginner',
    'duration' => '12week',
    'language' => 'English',
    'prerequisites' => 
    array (
    ),
    'category' => 'D.S.A',
    'tags' => 
    array (
    ),
    'syllabus' => 
    array (
    ),
    'resources' => 
    array (
    ),
    'related' => 
    array (
    ),
  ),
  'wwwyoutubecom' => 
  array (
    'title' => 'Machine Learning',
    'short' => 'hello',
    'description' => 'i am ml',
    'thumb' => '../uploads/thumbnails/wwwyoutubecom-1762750264.jpg',
    'instructor' => 'ankush joon',
    'level' => 'Intermediate',
    'duration' => '12',
    'language' => 'English',
    'intro_video_id' => 'https://youtu.be/LvC68w9JS4Y?si=PtF0yZTmrYFBUuU8',
    'prerequisites' => 
    array (
    ),
    'category' => 'AI',
    'tags' => 
    array (
    ),
    'syllabus' => 
    array (
    ),
    'resources' => 
    array (
    ),
    'related' => 
    array (
    ),
  ),
);
