<?php
session_start();
require_once "../client/db_connect.php";


// --- Config & Helpers ---
$study_content_file = __DIR__ . '/../client/study_content.php';
function esc($s){ return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
function active_class($page_name) {
    $current_page = basename($_SERVER['PHP_SELF']);
    if ($current_page === 'manage_courses.php' || $current_page === 'edit_courses.php') {
        if ($page_name === 'manage_courses.php') echo 'class="active"';
    } elseif ($current_page === $page_name) {
        echo 'class="active"';
    }
}

// --- Data Loading ---
$all_courses = file_exists($study_content_file) ? (include $study_content_file) : [];

$message = $_SESSION['message'] ?? null;
unset($_SESSION['message']);

// --- Handle Form Submission (POST) ---
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['course_slug'])) {
    $slug = trim($_POST['course_slug']);
    if (empty($slug)) {
        $_SESSION['message'] = ['type' => 'error', 'text' => 'Course Slug cannot be empty.'];
    } else {
        // Sanitize slug: lowercase, alphanumeric, and dashes
        $slug = strtolower(preg_replace('/[^a-zA-Z0-9-]+/', '', str_replace(' ', '-', $slug)));

        $is_new = !isset($all_courses[$slug]);
        $course_data = $all_courses[$slug] ?? [
            'title' => '', 'short' => '', 'description' => '', 'thumb' => '../images/course_placeholder.jpg',
            'instructor' => '', 'level' => 'Beginner', 'duration' => '', 'language' => 'English', 'intro_video_id' => '',
            'prerequisites' => [], 'category' => '', 'tags' => [], 'syllabus' => [], 'resources' => [], 'related' => []
        ];

        // Update fields from POST
        $course_data['title'] = trim($_POST['title'] ?? '');
        $course_data['short'] = trim($_POST['short'] ?? '');
        $course_data['thumb'] = trim($_POST['current_thumb'] ?? $course_data['thumb']); // Keep old thumb by default

        // --- Handle Thumbnail Upload ---
        if (isset($_FILES['thumb_image']) && $_FILES['thumb_image']['error'] === UPLOAD_ERR_OK) {
            $thumb_file = $_FILES['thumb_image'];
            $target_dir = __DIR__ . "/../uploads/thumbnails/";
            if (!is_dir($target_dir)) {
                mkdir($target_dir, 0755, true);
            }

            $image_info = getimagesize($thumb_file["tmp_name"]);
            $image_ext = strtolower(pathinfo($thumb_file["name"], PATHINFO_EXTENSION));
            $allowed_exts = ['jpg', 'jpeg', 'png', 'gif'];

            if ($image_info === false) {
                $_SESSION['message'] = ['type' => 'error', 'text' => 'Uploaded file is not a valid image.'];
            } elseif ($thumb_file["size"] > 2000000) { // 2MB limit
                $_SESSION['message'] = ['type' => 'error', 'text' => 'Image file is too large (max 2MB).'];
            } elseif (!in_array($image_ext, $allowed_exts)) {
                $_SESSION['message'] = ['type' => 'error', 'text' => 'Only JPG, JPEG, PNG, and GIF files are allowed.'];
            } else {
                $new_thumb_name = $slug . '-' . time() . '.' . $image_ext;
                $target_file = $target_dir . $new_thumb_name;
                if (move_uploaded_file($thumb_file["tmp_name"], $target_file)) {
                    // Path should be relative to the client folder where it's used
                    $course_data['thumb'] = '../uploads/thumbnails/' . $new_thumb_name;
                }
            }
        }

        $course_data['description'] = trim($_POST['description'] ?? '');
        $course_data['instructor'] = trim($_POST['instructor'] ?? '');
        $course_data['intro_video_id'] = trim($_POST['intro_video_id'] ?? '');
        $course_data['level'] = trim($_POST['level'] ?? 'Beginner');
        $course_data['duration'] = trim($_POST['duration'] ?? '');
        $course_data['category'] = trim($_POST['category'] ?? '');

        $all_courses[$slug] = $course_data;

        // Save back to file
        $output = "<?php\n\n// This file is auto-generated by the admin editor. Do not modify manually.\n\nreturn " . var_export($all_courses, true) . ";\n";
        if (file_put_contents($study_content_file, $output, LOCK_EX)) {
            $_SESSION['message'] = ['type' => 'success', 'text' => 'Course ' . ($is_new ? 'created' : 'updated') . ' successfully!'];
        } else {
            $_SESSION['message'] = ['type' => 'error', 'text' => 'Error saving course data. Check file permissions.'];
        }
    }
    header("Location: edit_courses.php");
    exit();
}

$edit_slug = $_GET['edit'] ?? null;
$course_to_edit = ($edit_slug && isset($all_courses[$edit_slug])) ? $all_courses[$edit_slug] : null;
if ($edit_slug === 'new') {
    $course_to_edit = ['is_new' => true]; // Flag for a new course form
}

$conn->close();
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="stylesheet" href="../client/style.css" />
  <link rel="shortcut icon" href="../images/logo.jpg" type="image/x-icon" />
  <title>Edit Courses • Admin</title>
  <style>
    :root { --primary: #0d6efd; --success: #198754; --danger: #dc3545; --light: #f4f7f9; --dark: #1e2227; --text-muted: #6c757d; --bg-surface: #fff; --border-color: #dee2e6; }
    body { background: var(--light); font-family: 'Segoe UI', sans-serif; }
    .dashboard-container { display: flex; min-height: 100vh; }
    .sidebar { background: var(--dark); color: #fff; width: 260px; display: flex; flex-direction: column; }
    .sidebar-brand { padding: 20px; display: flex; align-items: center; gap: 12px; background: #343a40; }
    .sidebar-brand img { width: 40px; height: 40px; border-radius: 50%; }
    .sidebar-brand-text { font-size: 1.2rem; font-weight: 600; }
    .sidebar-nav { flex-grow: 1; padding: 20px 0; }
    .sidebar-nav a { display: flex; align-items: center; gap: 12px; padding: 14px 20px; color: #adb5bd; text-decoration: none; transition: background 0.2s, color 0.2s; border-left: 4px solid transparent; }
    .sidebar-nav a:hover { background: #343a40; color: #fff; }
    .sidebar-nav a.active { background: var(--primary); color: #fff; border-left-color: #fff; font-weight: 600; }
    .sidebar-nav a .icon { width: 20px; height: 20px; }
    .main-content { flex: 1; padding: 40px; }
    .page-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }
    .page-header h1 { color: #343a40; font-size: 2.2rem; margin:0; }
    .btn { padding: 10px 18px; border-radius: 8px; text-decoration: none; font-weight: 600; border: none; cursor: pointer; display: inline-block; }
    .btn-primary { background: var(--primary); color: #fff; }
    .btn-success { background: var(--success); color: #fff; }
    .btn-secondary { background: #6c757d; color: #fff; }
    .message { padding: 15px; border-radius: 8px; margin-bottom: 20px; font-weight: 500; }
    .message.success { background: #d1e7dd; color: #0f5132; border: 1px solid #badbcc; }
    .message.error { background: #f8d7da; color: #842029; border: 1px solid #f5c2c7; }
    .course-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 24px; }
    .course-card { background: #fff; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); overflow: hidden; display: flex; flex-direction: column; transition: transform 0.2s; }
    .course-card:hover { transform: translateY(-5px); }
    .course-card-thumb { width: 100%; height: 160px; object-fit: cover; }
    .course-card-body { padding: 20px; flex-grow: 1; display: flex; flex-direction: column; }
    .course-card-body h3 { margin: 0 0 8px 0; font-size: 1.2rem; }
    .course-card-body p { margin: 0 0 16px 0; color: var(--text-muted); font-size: 0.95rem; flex-grow: 1; }
    .course-card-footer { display: flex; justify-content: space-between; align-items: center; }
    .course-card-footer .tag { background: #e9ecef; color: #495057; padding: 4px 8px; border-radius: 6px; font-size: 0.8rem; font-weight: 600; }
    .form-card { background: #fff; padding: 30px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); max-width: 800px; margin: 0 auto; }
    .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .input-group { margin-bottom: 20px; }
    .input-group.full-width { grid-column: 1 / -1; }
    .input-group label { display: block; font-weight: 600; margin-bottom: 6px; color: #495057; }
    .input-group input, .input-group textarea, .input-group select { width: 100%; padding: 10px; border: 1px solid var(--border-color); border-radius: 6px; font-size: 1rem; }
    .input-group textarea { min-height: 120px; resize: vertical; }
    .thumb-preview { width: 100px; height: auto; border-radius: 6px; margin-top: 8px; }
    .form-actions { display: flex; gap: 12px; margin-top: 20px; border-top: 1px solid var(--border-color); padding-top: 20px; }
  </style>
</head>
<body>
  <div class="dashboard-container">
    <aside class="sidebar">
      <div class="sidebar-brand"><img src="../images/logo.jpg" alt="logo"><span class="sidebar-brand-text">L.M.S Admin</span></div>
      <nav class="sidebar-nav">
        <a href="index.php" <?php active_class('index.php'); ?>><svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" /></svg><span>Dashboard</span></a>
        <a href="manage_courses.php" <?php active_class('manage_courses.php'); ?>><svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.246 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" /></svg><span>Courses</span></a>
        <a href="users.php" <?php active_class('users.php'); ?>><svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M15 21a6 6 0 00-9-5.197" /></svg><span>Users</span></a>
        <a href="certification.php" <?php active_class('certification.php'); ?>>
            <svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" /></svg>
            <span>Certification</span>
        </a>
        <a href="submissions.php" <?php active_class('submissions.php'); ?>>
            <svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
            <span>Submissions</span>
        </a>
        <a href="settings.php" <?php active_class('settings.php'); ?>><svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg><span>Settings</span></a>
        <a href="logout.php"><svg class="icon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg><span>Logout</span></a>
      </nav>
    </aside>

    <main class="main-content">
      <?php if ($message): ?>
        <div class="message <?php echo esc($message['type']); ?>"><?php echo esc($message['text']); ?></div>
      <?php endif; ?>

      <?php if ($course_to_edit): // Show Edit/New Form ?>
        <header class="page-header">
          <h1><?php echo isset($course_to_edit['is_new']) ? 'Add New Course' : 'Edit Course'; ?></h1>
          <a href="edit_courses.php" class="btn btn-secondary">&larr; Back to All Courses</a>
        </header>
        <div class="form-card">
          <form action="edit_courses.php" method="POST" enctype="multipart/form-data">
            <div class="form-grid">
              <div class="input-group">
                <label for="title">Course Title</label>
                <input type="text" id="title" name="title" value="<?php echo esc($course_to_edit['title'] ?? ''); ?>" required>
              </div>
              <div class="input-group">
                <label for="course_slug">Course Slug (URL)</label>
                <input type="text" id="course_slug" name="course_slug" value="<?php echo esc($edit_slug === 'new' ? '' : $edit_slug); ?>" <?php if($edit_slug !== 'new') echo 'readonly'; ?> placeholder="e.g., my-new-course">
                <?php if($edit_slug !== 'new'): ?><small class="text-muted">Slug cannot be changed after creation.</small><?php endif; ?>
              </div>
              <div class="input-group full-width">
                <label for="short">Short Description</label>
                <input type="text" id="short" name="short" value="<?php echo esc($course_to_edit['short'] ?? ''); ?>">
              </div>
              <div class="input-group full-width">
                <label for="description">Full Description</label>
                <textarea id="description" name="description"><?php echo esc($course_to_edit['description'] ?? ''); ?></textarea>
              </div>
              <div class="input-group full-width">
                <label for="thumb_image">Course Thumbnail</label>
                <input type="file" id="thumb_image" name="thumb_image" accept="image/*">
                <?php if (!empty($course_to_edit['thumb'])): ?>
                    <p style="margin-top:8px;font-size:0.9rem;">Current Thumbnail:</p>
                    <img src="<?php echo esc($course_to_edit['thumb']); ?>" alt="Current Thumbnail" class="thumb-preview">
                    <input type="hidden" name="current_thumb" value="<?php echo esc($course_to_edit['thumb']); ?>">
                <?php endif; ?>
              </div>
              <div class="input-group">
                <label for="instructor">Instructor</label>
                <input type="text" id="instructor" name="instructor" value="<?php echo esc($course_to_edit['instructor'] ?? ''); ?>">
              </div>
              <div class="input-group">
                <label for="intro_video_id">Intro Video ID (YouTube)</label>
                <input type="text" id="intro_video_id" name="intro_video_id" value="<?php echo esc($course_to_edit['intro_video_id'] ?? ''); ?>" placeholder="e.g., 1Rs2ND_M_sE">
              </div>
              <div class="input-group">
                <label for="category">Category</label>
                <input type="text" id="category" name="category" value="<?php echo esc($course_to_edit['category'] ?? ''); ?>" placeholder="e.g., web, design, data">
              </div>
              <div class="input-group">
                <label for="level">Level</label>
                <select id="level" name="level">
                  <option value="Beginner" <?php if (($course_to_edit['level'] ?? '') === 'Beginner') echo 'selected'; ?>>Beginner</option>
                  <option value="Intermediate" <?php if (($course_to_edit['level'] ?? '') === 'Intermediate') echo 'selected'; ?>>Intermediate</option>
                  <option value="Advanced" <?php if (($course_to_edit['level'] ?? '') === 'Advanced') echo 'selected'; ?>>Advanced</option>
                </select>
              </div>
              <div class="input-group">
                <label for="duration">Duration</label>
                <input type="text" id="duration" name="duration" value="<?php echo esc($course_to_edit['duration'] ?? ''); ?>" placeholder="e.g., 8 Weeks">
              </div>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-success">Save Course</button>
              <a href="edit_courses.php" class="btn btn-secondary">Cancel</a>
            </div>
          </form>
        </div>

      <?php else: // Show Course Grid ?>
        <header class="page-header">
          <h1>Course Content</h1>
          <a href="edit_courses.php?edit=new" class="btn btn-primary">Add New Course</a>
        </header>
        <div class="course-grid">
          <?php foreach ($all_courses as $slug => $course): ?>
            <div class="course-card">
              <img src="<?php echo esc($course['thumb'] ?? '../images/course_placeholder.jpg'); ?>" alt="" class="course-card-thumb">
              <div class="course-card-body">
                <h3><?php echo esc($course['title']); ?></h3>
                <p><?php echo esc($course['short']); ?></p>
                <div class="course-card-footer">
                  <span class="tag"><?php echo esc($course['level'] ?? 'N/A'); ?></span>
                  <a href="edit_courses.php?edit=<?php echo urlencode($slug); ?>" class="btn btn-primary">Edit</a>
                </div>
              </div>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
    </main>
  </div>
</body>
</html>